version: '3.6'

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
    - ./postgres:/data/postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  graphql-engine:
    container_name: "hasura-engine"
    build:
      context: ./hasura
      dockerfile: ./Dockerfile
      args:
        HASURA_GRAPHQL_DEV_MODE: "true"
        HASURA_GRAPHQL_ADMIN_SECRET: "dev"
        ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
        HASURA_GRAPHQL_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
        ## postgres database to store Hasura metadata
        HASURA_GRAPHQL_METADATA_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

    ports:
      - "8080:8080"
    volumes:
      - ./hasura:/hasura
    depends_on:
      - postgres
    restart: always
